-- NewsReal V5 Real Estate migration
-- Chạy đúng 1 lần trên database hiện tại.

ALTER TABLE posts ADD COLUMN "transaction" TEXT DEFAULT '';
ALTER TABLE posts ADD COLUMN property_type TEXT DEFAULT '';
ALTER TABLE posts ADD COLUMN unit_price TEXT DEFAULT '';
ALTER TABLE posts ADD COLUMN bedrooms INTEGER;
ALTER TABLE posts ADD COLUMN bathrooms INTEGER;
ALTER TABLE posts ADD COLUMN floors INTEGER;
ALTER TABLE posts ADD COLUMN direction TEXT DEFAULT '';
ALTER TABLE posts ADD COLUMN legal TEXT DEFAULT '';
ALTER TABLE posts ADD COLUMN furniture TEXT DEFAULT '';
ALTER TABLE posts ADD COLUMN province TEXT DEFAULT '';
ALTER TABLE posts ADD COLUMN district TEXT DEFAULT '';
ALTER TABLE posts ADD COLUMN ward TEXT DEFAULT '';
ALTER TABLE posts ADD COLUMN gallery TEXT DEFAULT '';
ALTER TABLE posts ADD COLUMN contact_name TEXT DEFAULT '';
ALTER TABLE posts ADD COLUMN featured INTEGER NOT NULL DEFAULT 0;
ALTER TABLE posts ADD COLUMN verified INTEGER NOT NULL DEFAULT 0;
ALTER TABLE posts ADD COLUMN listing_code TEXT DEFAULT '';
ALTER TABLE posts ADD COLUMN frontage TEXT DEFAULT '';
