-- V20.9.14 Template Marketplace SEO + Game preview
-- Non-destructive: catalog metadata only.
UPDATE template_catalog SET seo_title='Template website bất động sản & tin tức – Cổng thông tin SEO', seo_slug='bat-dong-san-tin-tuc-portal', primary_keyword='template website bất động sản', secondary_keywords='mẫu website bất động sản, website tin tức bất động sản, giao diện website nhà đất', meta_description='Mẫu website bất động sản kết hợp tin tức, nhiều chuyên mục, trang bài chi tiết và cấu trúc nội dung phù hợp xây dựng SEO dài hạn.', internal_anchor='template website bất động sản', updated_at=CURRENT_TIMESTAMP WHERE template_key='mau-1';
UPDATE template_catalog SET seo_title='Template website bất động sản hiện đại – Tìm kiếm & chuyển đổi', seo_slug='bat-dong-san-hien-dai', primary_keyword='mẫu website bất động sản hiện đại', secondary_keywords='template nhà đất, website môi giới bất động sản, giao diện website bất động sản', meta_description='Template bất động sản hiện đại với hero tìm kiếm, card dự án và bố cục tối ưu trải nghiệm mobile, phù hợp môi giới và doanh nghiệp nhà đất.', internal_anchor='mẫu website bất động sản hiện đại', updated_at=CURRENT_TIMESTAMP WHERE template_key='mau-2';
UPDATE template_catalog SET seo_title='Template website bất động sản cao cấp – Luxury Real Estate', seo_slug='bat-dong-san-luxury', primary_keyword='template website bất động sản cao cấp', secondary_keywords='mẫu website luxury, website biệt thự cao cấp, giao diện bất động sản sang trọng', meta_description='Mẫu website bất động sản cao cấp phong cách luxury editorial, hình ảnh lớn và bố cục sang trọng cho biệt thự, dự án và môi giới cao cấp.', internal_anchor='template bất động sản cao cấp', updated_at=CURRENT_TIMESTAMP WHERE template_key='mau-3';
UPDATE template_catalog SET seo_title='Template website bất động sản tối giản – Nhanh, dễ xem, chuẩn SEO', seo_slug='bat-dong-san-minimal-seo', primary_keyword='template website bất động sản tối giản', secondary_keywords='mẫu website nhà đất tối giản, website bất động sản nhanh, giao diện bất động sản SEO', meta_description='Template bất động sản tối giản, tải nhanh, tập trung ảnh, giá và thông tin quan trọng; phù hợp website nhà đất cần trải nghiệm rõ ràng và SEO.', internal_anchor='template bất động sản tối giản', updated_at=CURRENT_TIMESTAMP WHERE template_key='mau-4';
UPDATE template_catalog SET seo_title='Template website bất động sản Urban – Mua bán & cho thuê', seo_slug='bat-dong-san-urban', primary_keyword='template website bất động sản mua bán cho thuê', secondary_keywords='mẫu website nhà đất urban, website mua bán nhà đất, website cho thuê bất động sản', meta_description='Mẫu website bất động sản Urban với khám phá khu vực, mua bán, cho thuê và CTA chuyển đổi rõ ràng cho môi giới và sàn nhà đất.', internal_anchor='template website mua bán nhà đất', updated_at=CURRENT_TIMESTAMP WHERE template_key='mau-5';
UPDATE template_catalog SET seo_title='Template website tin tức hiện đại – Tạp chí & cổng nội dung', seo_slug='tin-tuc-tap-chi-hien-dai', primary_keyword='template website tin tức', secondary_keywords='mẫu website tin tức, giao diện báo điện tử, template tạp chí online', meta_description='Template website tin tức hiện đại với bài nổi bật, tin mới, chuyên mục và nội dung đọc nhiều; phù hợp báo điện tử, tạp chí và site nội dung.', internal_anchor='template website tin tức', updated_at=CURRENT_TIMESTAMP WHERE template_key='tin-tuc-1';
UPDATE template_catalog SET seo_title='Template báo điện tử – Website tin tức mật độ cao', seo_slug='bao-dien-tu', primary_keyword='template báo điện tử', secondary_keywords='mẫu báo điện tử, website tin tổng hợp, giao diện website tin tức', meta_description='Mẫu báo điện tử với headline lớn, danh sách cập nhật liên tục, chuyên mục và khu đọc nhiều, phù hợp website tin tổng hợp có mật độ nội dung cao.', internal_anchor='template báo điện tử', updated_at=CURRENT_TIMESTAMP WHERE template_key='tin-tuc-2';
UPDATE template_catalog SET seo_title='Template website tạp chí – Magazine hiện đại nhiều hình ảnh', seo_slug='tin-tuc-magazine', primary_keyword='template website tạp chí', secondary_keywords='mẫu magazine online, website lifestyle, template tin công nghệ', meta_description='Template tạp chí online với hero mosaic, Editor Pick, Trending và card hình ảnh hiện đại, phù hợp lifestyle, công nghệ và nội dung chuyên ngành.', internal_anchor='template website tạp chí', updated_at=CURRENT_TIMESTAMP WHERE template_key='tin-tuc-3';
UPDATE template_catalog SET seo_title='Template website tin tức chuẩn SEO – Minimal, nhẹ và nhanh', seo_slug='tin-tuc-minimal-seo', primary_keyword='template website tin tức chuẩn SEO', secondary_keywords='mẫu blog SEO, website tin tức nhẹ, template nội dung tốc độ cao', meta_description='Template tin tức tối giản ưu tiên tốc độ, typography dễ đọc và mật độ nội dung tốt, phù hợp blog chuyên ngành và chiến lược SEO nội dung.', internal_anchor='template tin tức chuẩn SEO', updated_at=CURRENT_TIMESTAMP WHERE template_key='tin-tuc-4';
UPDATE template_catalog SET seo_title='Template website FPT – Internet, FPT Play, Camera & Combo', seo_slug='website-dich-vu-fpt', primary_keyword='template website FPT', secondary_keywords='mẫu website internet FPT, website FPT Play, landing page dịch vụ FPT', meta_description='Template website dịch vụ FPT với Internet, FPT Play, Camera AI, combo và CTA tư vấn rõ ràng, phù hợp đại lý và nhân viên kinh doanh FPT.', internal_anchor='template website FPT', updated_at=CURRENT_TIMESTAMP WHERE template_key='dich-vu-1';
UPDATE template_catalog SET seo_title='Template website VNPT – Home Internet, MyTV & Home Cam', seo_slug='website-dich-vu-vnpt', primary_keyword='template website VNPT', secondary_keywords='mẫu website VNPT, website MyTV, landing page Home Internet VNPT', meta_description='Template website VNPT với Home Internet, MyTV, Home Cam, combo gia đình và CTA tư vấn, phù hợp đại lý và nhân viên kinh doanh VNPT.', internal_anchor='template website VNPT', updated_at=CURRENT_TIMESTAMP WHERE template_key='dich-vu-2';
UPDATE template_catalog SET seo_title='Template website Viettel – Internet, TV360 & Camera', seo_slug='website-dich-vu-viettel', primary_keyword='template website Viettel', secondary_keywords='mẫu website Viettel, website TV360, landing page internet Viettel', meta_description='Template website Viettel với Internet Wi-Fi, TV360, Camera Cloud, combo và CTA đăng ký, phù hợp đại lý và nhân viên kinh doanh Viettel.', internal_anchor='template website Viettel', updated_at=CURRENT_TIMESTAMP WHERE template_key='dich-vu-3';
UPDATE template_catalog SET seo_title='Template website bán Camera – Catalog sản phẩm & tư vấn', seo_slug='website-camera', primary_keyword='template website camera', secondary_keywords='mẫu website camera, website bán camera, catalog camera an ninh', meta_description='Template website camera đa thương hiệu với catalog sản phẩm, giá, thông số, khuyến mãi, trang chi tiết và form tư vấn khách hàng.', internal_anchor='template website camera', updated_at=CURRENT_TIMESTAMP WHERE template_key='dich-vu-4';
UPDATE template_catalog SET seo_title='Template website Clash of Clans – Chia sẻ base TH/BH/CH', seo_slug='clash-of-clans-base', primary_keyword='template website Clash of Clans', secondary_keywords='mẫu website game, website chia sẻ base Clash of Clans, template game Clash of Clans', meta_description='Template website Clash of Clans chuyên chia sẻ base Town Hall, Builder Hall và Clan Capital với bộ lọc nhanh, copy link và trang chi tiết tối ưu SEO.', internal_anchor='template website Clash of Clans', updated_at=CURRENT_TIMESTAMP WHERE template_key='game-1';
UPDATE template_catalog SET image_url='/assets/demo/game-clash-1-preview.png', updated_at=CURRENT_TIMESTAMP WHERE template_key='game-1';
